### ISSUE TITLE
Error with Name Pain

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/menucompanions#2]
`Minecraft v1.15.2`
`Forge v32.1.36`
`Menu Companions v1.0.0`
[`Name Pain v1.3.0-Forge`](https://www.curseforge.com/minecraft/mc-mods/name-pain/files/3055730)

Soon after the posting of the other issue, I realized that my log was being spammed with an error being caused by this mod and Name Pain, and the player and the bee was being added to the blacklist, but it did not stop them from rendering and causing errors. Name Pain is a mod that changes the name tag, it turns more red the more damage an entity takes. Here is the [log](https://gist.github.com/WenXin20/c7990455ade1ccf78352aecec509c212).

**Comment by Fuzss** [comment]
Fixed in 9871304, will be part of v1.0.2 on Curse

**Comment by naqaden** [comment]
This is also fixed on Name Pain's end in the upcoming v1.4 update, as other menu mods had similar issues.
