### ISSUE TITLE
Broken Main Menu w/ Ice and Fire

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/menucompanions#6]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Menu Companions v1.1`
`Ice & Fire v2.1.5`

After adding the mod Ice and Fire to my modpack, menu displays incorrectly. Removing either mod fixes the menu.

![2021-01-22_18 41 44](https://user-images.githubusercontent.com/12000593/105562932-dff98200-5ce1-11eb-964b-7cfdb0fff1c2.png)

**Comment by Fuzss** [comment]
Fixed in v1.2.1.
