### ISSUE TITLE
entities not appearing in v1.1-1.16.5 (latest), fancy menu installed, this issue doesn't exist in v1.0.2-1.16.3

### ISSUE THREAD

**Issue by Wedge1453** [Fuzss/menucompanions#7]
using forge 35.1.36 (in 1.16.4), while customizing with fancy menu the mod detects the 2 entity spots as buttons, but they're invisible and can't be interacted with (no sound when clicked), with the second newest version it works, fancy meny doesn't detect the  spots as buttons (as far as I remember).

**Comment by Fuzss** [comment]
You probably still have the old config file (`mobs.json` in the `config/menucompanions` directory) from v1.0.2. Delete that so it can be regenerated and report back if it works.

**Comment by Wedge1453** [comment]
I updated to the latest version and deleted the old config, same problem, I also didn't notice any difference between the old configs and the new ones.

**Comment by Fuzss** [comment]
Fixed in v1.2.
