### ISSUE TITLE
companions getting blacklisted

### ISSUE THREAD

**Issue by Wedge1453** [Fuzss/menucompanions#8]
after upadting to the latest version I re-wrote my settings in the new format and tested, it worked fine, then after a couple days I updated some mods and loaded my mod-pack and the companions weren't rendering, first i removed the mods I updated, it didn't solve the problem, then I did a dichotomic search to find which mod caused incompatibility with menu companions and I couldn't find any, I tried with a fresh config folder (all mods), the problem persisted, I tried downgrading the mod version but surprisingly it didnt solve the problem, I loaded menu companions alone and it worked, I have no idea what to do now, I doubt this poor description of the problem helps solving it, that's all the info I could gather.

**Comment by Fuzss** [comment]
When the issue occurs, please send your `latest.log` found in `.minecraft/logs`.

**Comment by Wedge1453** [comment]
ok so I did more tests, I disabled mods 10 by 10, in the end I had menu companions alone and it wasn't working, I remembered that I didn't delete the client config file previously so I did that, the companions apeared, I re-enabled all the mods and they disapeared again, so I thought it might be due to mod incompatibility + the client config file, I started disabling mods again and same result, I ended up with menu companions alone again, no companions, so I thought something is wrong with the client config file...
I started messing with the later, I noticed that when I change the companions display time and save, the client configs resets and the old one gets the .bak extension, I also noticed that after saving and clicking the refresh button in-game, the companions names start flickering for a second then disapear, only the name tags, the companions still dont show up. I think something similar happened with companions size too.

here is the latest.log file: 
[latest.log](https://github.com/Fuzss/menucompanions/files/6144037/latest.log)

**Comment by Fuzss** [comment]
Thanks a lot for all the effort you've put into this!

So Menu Companions not rendering anything when it's the only mod left is intended in your case. There must be at least one other mod which somehow hooks into the rendering of all entities, causing it to fail when Menu Companions tries to add mobs to the main menu. To prevent a game crash, Menu Companions detects that crash and adds the problematic entity to a blacklist in the `menucompanions-client.toml` config file.

Entries can only be removed manually from that blacklist, so even after uninstalling all other mods the blacklist will basically contain every entity in the game, causing Menu Companions not to render anything.

So to find the incompatible mod you also need to delete the `menucompanions-client.toml` file every time before starting your game.

**Comment by Fuzss** [comment]
Can you please test [this custom version](https://mega.nz/file/zVtWWTRY#BrnmpStppS2XFw77kIYzlS7FQbM8EKASTNfZ--RoA5U)? It should crash when rendering the main menu, the crash-report is what I need then.

**Comment by Wedge1453** [comment]
so I ran 2 tests, in the first I kept the menucompanions folder I had, here is the crash log:
[crash-2021-03-16_15.22.55-client.txt](https://github.com/Fuzss/menucompanions/files/6151053/crash-2021-03-16_15.22.55-client.txt)
in the second I removed that folder so that the mod generates a fresh one, here's the crash log:
[crash-2021-03-16_17.16.31-client.txt](https://github.com/Fuzss/menucompanions/files/6151060/crash-2021-03-16_17.16.31-client.txt)

I didn't touch the config file, and here is the modpack I'm using menu companions with: https://www.curseforge.com/minecraft/modpacks/dungeons-and-creations
thank you for your reply, let me know if you need me to do more tests!

**Comment by Fuzss** [comment]
Awesome, that's all I needed. The incompatible mod is Two Players One Horse by Beethoven92.

I'll have to see what I can do about that.

**Comment by Fuzss** [comment]
The crash happens inside of a mixin, so I'm not sure that I can really do anything about that. I've created [an issue](https://www.curseforge.com/minecraft/mc-mods/two-players-one-horse/issues/1) on Two Players One Horse's issue tracker for them to fix it on their end, since all that's required is a simple null check.

**Comment by Wedge1453** [comment]
I removed Two Players One Horse and removed the mobs from the blacklist, it worked! thank you very much for your time!!

**Comment by Wedge1453** [comment]
hello again, so I noticed that some mobs don't show up anymore, I found them in the config blacklist, I removed them and kept watching the blacklist, it was slowly filling up with mobs like "conjurer_illager:conjurer", "minecraft:pillager", "minecraft:illusioner", "minecraft:vindicator", "hunterillager:hunterillager", "savageandravage:griefer", "enchantwithmob:enchanter"
btw I have a display time > 0

**Comment by Fuzss** [comment]
Another mod must be hooking into the rendering of all illagers then. Can you use the test version from above once more? The crash will then tell which mod it is.

**Comment by Wedge1453** [comment]
[crash-2021-03-21_20.02.53-client.txt](https://github.com/Fuzss/menucompanions/files/6178275/crash-2021-03-21_20.02.53-client.txt)
looks like it's because of banners additions
it's not a big problem if display time = 0, in that case it takes very long for a mob to get blacklisted, the test version of the mod didn't even crash the game at display time = 0.
if I keep getting that paroblem after I remove banners additions, I should use the test version again right?

**Comment by Fuzss** [comment]
It's because of the banner which is rendered on the head of an illager patrol leader. Now just let the blacklist do its work by filtering out the illagers. I'm content with that behavior, as long as the mod keeps working fine otherwise. So closing this ticket now.

**Comment by Wedge1453** [comment]
ok I'll keep display time at 0 then, thank you for your help!

**Comment by Fuzss** [comment]
No you can set whatever value you like, the blacklist will catch faulty entries anyways and prevent them from reappearing.

**Comment by Fuzss** [comment]
Also the issue with Two Players One Horse has been fixed on their end.

**Comment by Wedge1453** [comment]
I know, I meant i will keep display time = 0 so it happens way slower than higher values
