### ISSUE TITLE
Crash w/ JourneyMap Waypoints Menu

### ISSUE THREAD

**Issue by ghost** [Fuzss/menucompanions#9]
`MC 1.16.5`
`Forge 36.0.45`
`MenuCompanions v1.2.2-1.16.5`
`JourneyMap 1.16.5-5.7.1`

Tried to teleport to a waypoint in JourneyMap's waypoints menu, and the game immediately crashed (to the menu only thanks to NotEnoughCrashes!).

Crash Report: https://hatebin.com/logjrlnega
Latest.log: https://hatebin.com/rwhevrzdqz

**Comment by Fuzss** [comment]
Fixed in v1.2.3.
